encryptionsalt: v1:HEY9oKCxG4s=:v1:VFZxijYuG+dmgduB:10/zcSCPl3NdW+dR5YEAHOCh9CuyEg==
config:
  gcp:project: i1ncx3d2imnb1k
  gcp:region: us-central1
  myapi-service:serviceName: myapi-staging
  myapi-service:artifactRegistryRepoId: myapi
  myapi-service:runtimeServiceAccountId: myapi-staging-runtime
  myapi-service:appEnv: staging
  myapi-service:usdaSecretName: USDA_API_KEY_STAGING
  myapi-service:deployerPrincipal: serviceAccount:github-myapi-staging@i1ncx3d2imnb1k.iam.gserviceaccount.com
  myapi-service:stagingInvokerMember: user:tnkvie@gmail.com
  myapi-service:minInstanceCount: "0"
  myapi-service:maxInstanceCount: "1"
  myapi-service:timeout: 60s
  myapi-service:cpuIdle: "true"
  myapi-service:startupCpuBoost: "false"
  myapi-service:runtimeServiceAccountEmail: myapi-staging-runtime@i1ncx3d2imnb1k.iam.gserviceaccount.com
  myapi-service:usdaSecretVersion: latest
  myapi-service:invokerMember: user:tnkvie@gmail.com
